name: Quarto Publish

on:
  push:
    branches: [main]  # or whatever your default branch is

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Jupyter and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbformat pandas numpy colour-science

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # - name: Render
      #   run: quarto render

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
